/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Thu, Jan 11, 2007                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
                  


#include	<machine.h>
#include	<_h_c_lib.h>
//#include	<stddef.h>					// Remove the comment when you use errno
//#include 	<stdlib.h>					// Remove the comment when you use rand()
#include	"typedefine.h"
#include	"stacksct.h"

#define SR_Init    0x000000F0
#define INT_OFFSET 0x10
#define FPSCR_Init 0x00040001 	/* cpu=sh2afpu|sh4|sh4a 指定時のみ*/
								/* fpu=double 指定時の初期値は0x00080001 */
								
extern _UINT INT_Vectors;

#ifdef __cplusplus
extern "C" {
#endif
void PowerON_Reset_PC(void);
void Manual_Reset_PC(void);
void main(void);
#ifdef __cplusplus
}
#endif

//#ifdef __cplusplus				// Use SIM I/O
//extern "C" {
//#endif
//extern void _INIT_IOLIB(void);
//extern void _CLOSEALL(void);
//#ifdef __cplusplus
//}
//#endif

//extern void srand(_UINT);		// Remove the comment when you use rand()
//extern _SBYTE *_s1ptr;				// Remove the comment when you use strtok()
		
//#ifdef __cplusplus				// Use Hardware Setup
//extern "C" {
//#endif
//extern void HardwareSetup(void);
//#ifdef __cplusplus
//}
//#endif
	
//#ifdef __cplusplus			// Remove the comment when you use global class object
//extern "C" {					// Sections C$INIT and C$END will be generated
//#endif
//extern void _CALL_INIT(void);
//extern void _CALL_END(void);
//#ifdef __cplusplus
//}
//#endif

#pragma section ResetPRG

#pragma entry PowerON_Reset_PC

#define DF_RAM_COPY_ADDR (0xFFF80000)
#define DF_ROM_COPY_ADDR (0)
#define DF_ROM_COPY_SIZE (0x10000)	/* コピーサイズ(バイト) */

void PowerON_Reset_PC(void)
{ 
	unsigned long ullLoop;
	unsigned long *pullFromAdr;
	unsigned long *pullToAdr;
	
	Init_Stack();
	set_vbr(0);
	set_fpscr(FPSCR_Init); /* cpu=sh2afpu|sh4|sh4a 指定時のみ設定してください*/
	
 	REG_INIT_BSC();						/* バスステートコントローラ初期化 RAMチェック前に実施*/
 	RAMCK();							/* RAM check & clear */

	RAMCOPY(DF_RAM_COPY_ADDR, DF_ROM_COPY_ADDR, DF_ROM_COPY_SIZE);

	set_vbr((void *)DF_RAM_COPY_ADDR); //ベクタテーブルを RAM にする

	_INITSCT();

//	_CALL_INIT();					// Remove the comment when you use global class object

//	_INIT_IOLIB();					// Use SIM I/O

//	errno=0;						// Remove the comment when you use errno
//	srand((_UINT)1);					// Remove the comment when you use rand()
//	_s1ptr=NULL;					// Remove the comment when you use strtok()
		
//	HardwareSetup();				// Use Hardware Setup
	set_cr(SR_Init);
    nop();

	main();

//	_CLOSEALL();					// Use SIM I/O
	
//	_CALL_END();					// Remove the comment when you use global class object

	sleep();
}

//#pragma entry Manual_Reset_PC		// Remove the comment when you use Manual Reset
void Manual_Reset_PC(void)	
{
}
