/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Thu, Jan 11, 2007                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x1000         /* Do not modify this line. */
