/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Thu, Oct 19, 2006                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :SH7058F                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.3.0).     */
/*                                                                     */
/***********************************************************************/
                  


#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup();
#ifdef __cplusplus
}
#endif


void HardwareSetup()
{
/*
  P_SCI0.SMR0.BYTE = 0;
  P_SCI0.SMR0.BIT.CA   = 1;
  P_SCI0.SMR0.BIT.CHR  = 1;
  P_SCI0.SMR0.BIT.OE   = 1;
  P_SCI0.SMR0.BIT.STOP = 1;
  P_SCI0.SMR0.BIT.MP   = 1;
  P_SCI0.SMR0.BIT.CKS  = 3;
*/
}
