/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Thu, Oct 19, 2006                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :SH7058F                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.3.0).     */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x400         /* Do not modify this line. */
